# This docker-compose file sets up n8n, Redis, and postgres with the vector plugin
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - aitoolkit
    volumes:
      - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    hostname: postgres
    networks:
      - aitoolkit
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HIRING_BANNER_ENABLED=false
      - WEBHOOK_URL=${N8N_HOSTNAME:+https://}${N8N_HOSTNAME:-http://localhost:5678}
      - N8N_HOST=${N8N_HOSTNAME:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    container_name: n8n
    hostname: n8n
    restart: unless-stopped
    networks:
      - aitoolkit
    expose:
      - 5678/tcp
    volumes:
      - n8n_storage:/home/node/.n8n
      # The local path for the shared volume is now configurable via the SHARED_DATA_PATH environment variable.
      # It defaults to './shared' if the variable is not set.
      - ${SHARED_DATA_PATH:-./shared}:/home/node/.n8n-files
    ports:
      - 5678:5678
    depends_on:
      postgres:
        condition: service_healthy

networks:
  aitoolkit:

volumes:
  n8n_storage:
  redis-data:
  postgres_storage:
